payload:
  - PROCESS-NAME,OneDrive.exe
  - PROCESS-NAME,OneDrive
  - PROCESS-NAME,rclone.exe
  - PROCESS-NAME,rclone
  - PROCESS-NAME,aDrive.exe
  - PROCESS-NAME,aDrive
  - PROCESS-NAME,XboxPcApp.exe
  - PROCESS-NAME,amazon.mshop
  - PROCESS-NAME,XboxPcAppFT.exe
  - PROCESS-NAME,nvcontainer.exe
  - PROCESS-NAME,XboxGameBarWidgets.exe
  - PROCESS-NAME,Microsoft Remote Desktop Beta.app
